[MODFQMMGR-72] Remove instance_title_searchable field
folio-org/mod-fqm-manager pull request #67
Opened 2023-11-02 18:16 UTC by ncovercash

## Purpose
`instance_title_searchable` was causing more problems than it was worth, so we removed it.

## Approach
Add new Liquibase changelogs to recreate the view and update the associated entity_type_definition.

## Learning
- Turns out Postgres [will not allow you to remove columns when running a `CREATE OR REPLACE VIEW` query](https://stackoverflow.com/questions/65117930/postgresql-error-cannot-drop-columns-from-view), so we have to drop it first.  We can assume it's already there, though, since previous version's changes will be created before this changelog is executed.

## Bonus
- ignore `.env` files

2023-11-02 19:15 UTC, kjain110 approved these changes

2023-11-02 19:23 UTC, bvsharp requested changes
The way things are set up right now, we have 2 different derived views with the instance_title_searchable field: drv_item_details and drv_item_holdingsrecord_instance. This will need to be removed from the view and entity type definition for both.

2023-11-03 15:52 UTC, bvsharp commented on src/main/resources/db/changelog/changes/v1.0.2/update_item_holdingsrecord_entity_type_definition.xml
> +              "name": "instance_title_searchable",
This entry should be removed

2023-11-03 15:52 UTC, ncovercash commented on src/main/resources/db/changelog/changes/v1.0.2/update_item_holdingsrecord_entity_type_definition.xml
> +              "name": "instance_title_searchable",
Doh, oops

2023-11-03 15:54 UTC, bvsharp approved these changes

2023-11-03 15:57 UTC, merged